use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::Path;

use crate::platform::{OperatingSystem, Target};

/// Linux/macOS için launcher script oluşturur
pub fn create_unix_launcher(output_dir: &Path, app_name: &str, script_name: &str) -> Result<(), String> {
    let launcher_content = format!(
        r#"#!/bin/bash
# {app_name} - Python Runtime Bundle
# This script launches the app with built-in Python runtime.

set -e

SCRIPT_DIR="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
PYTHON_DIR="$SCRIPT_DIR/python"
PYTHON_BIN="$PYTHON_DIR/bin/python3"

if [[ "$(uname)" == "Linux" ]]; then
    export LD_LIBRARY_PATH="$PYTHON_DIR/lib:$LD_LIBRARY_PATH"
fi

if [[ "$(uname)" == "Darwin" ]]; then
    export DYLD_LIBRARY_PATH="$PYTHON_DIR/lib:$DYLD_LIBRARY_PATH"
    export DYLD_FRAMEWORK_PATH="$PYTHON_DIR/lib:$DYLD_FRAMEWORK_PATH"
fi

export PYTHONHOME="$PYTHON_DIR"
export PYTHONPATH="$SCRIPT_DIR/lib:$PYTHON_DIR/lib/python3.11/site-packages"
export PYTHONNOUSERSITE=1
export PYTHONDONTWRITEBYTECODE=1

exec "$PYTHON_BIN" "$SCRIPT_DIR/app/{script_name}" "$@"
"#,
        app_name = app_name,
        script_name = script_name,
    );

    let launcher_path = output_dir.join(app_name);
    fs::write(&launcher_path, launcher_content)
        .map_err(|e| format!("Couldn't create the launcher: {}", e))?;

    // Çalıştırılabilir yap
    let metadata = fs::metadata(&launcher_path)
        .map_err(|e| format!("Couldn't read the metadata: {}", e))?;
    let mut perms = metadata.permissions();
    perms.set_mode(0o755);
    fs::set_permissions(&launcher_path, perms)
        .map_err(|e| format!("Couldn't set the permissions: {}", e))?;

    Ok(())
}

/// Windows için launcher batch dosyası oluşturur
pub fn create_windows_launcher(output_dir: &Path, app_name: &str, script_name: &str) -> Result<(), String> {
    let launcher_content = format!(
        r#"@echo off
REM {app_name} - Python Runtime Bundle
REM This script launches the app with built-in Python runtime.

setlocal

set SCRIPT_DIR=%~dp0
set PYTHON_DIR=%SCRIPT_DIR%python
set PYTHON_BIN=%PYTHON_DIR%\python.exe

set PYTHONHOME=%PYTHON_DIR%
set PYTHONPATH=%SCRIPT_DIR%lib;%PYTHON_DIR%\Lib\site-packages
set PYTHONNOUSERSITE=1
set PYTHONDONTWRITEBYTECODE=1

"%PYTHON_BIN%" "%SCRIPT_DIR%app\{script_name}" %*

endlocal
"#,
        app_name = app_name,
        script_name = script_name,
    );

    let launcher_path = output_dir.join(format!("{}.bat", app_name));
    fs::write(&launcher_path, launcher_content)
        .map_err(|e| format!("Couldn't create Windows launcher: {}", e))?;

    // PowerShell script de oluştur
    let ps_content = format!(
        r#"# {app_name} - PowerShell Launcher
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$PythonDir = Join-Path $ScriptDir "python"
$PythonBin = Join-Path $PythonDir "python.exe"

$env:PYTHONHOME = $PythonDir
$env:PYTHONPATH = Join-Path $ScriptDir "lib"
$env:PYTHONNOUSERSITE = "1"
$env:PYTHONDONTWRITEBYTECODE = "1"

& $PythonBin (Join-Path $ScriptDir "app" "{script_name}") @args
"#,
        app_name = app_name,
        script_name = script_name,
    );

    let ps_path = output_dir.join(format!("{}.ps1", app_name));
    fs::write(&ps_path, ps_content)
        .map_err(|e| format!("Couldn't create PowerShell launcher: {}", e))?;

    Ok(())
}

/// Rust tabanlı binary launcher kaynak kodu oluşturur
pub fn generate_rust_launcher_source(app_name: &str, script_name: &str) -> String {
    format!(
        r#"// Auto-generated launcher for {app_name}
// This file is generated by pypack

use std::path::PathBuf;
use std::process::Command;

fn main() {{
    let exe_dir = std::env::current_exe()
        .ok()
        .and_then(|p| p.parent().map(|p| p.to_path_buf()))
        .unwrap_or_else(|| PathBuf::from("."));

    #[cfg(target_os = "windows")]
    let python_bin = exe_dir.join("python").join("python.exe");

    #[cfg(not(target_os = "windows"))]
    let python_bin = exe_dir.join("python").join("bin").join("python3");

    #[cfg(target_os = "windows")]
    let script_path = exe_dir.join("app").join("{script_name}");

    #[cfg(not(target_os = "windows"))]
    let script_path = exe_dir.join("app").join("{script_name}");

    #[cfg(target_os = "linux")]
    {{
        let lib_dir = exe_dir.join("python").join("lib");
        if let Some(lib_str) = lib_dir.to_str() {{
            let ld_path = std::env::var("LD_LIBRARY_PATH").unwrap_or_default();
            std::env::set_var("LD_LIBRARY_PATH", format!("{{}}:{{}}", lib_str, ld_path));
        }}
    }}

    let python_home = exe_dir.join("python");
    std::env::set_var("PYTHONHOME", &python_home);

    let mut cmd = Command::new(&python_bin);
    cmd.arg(&script_path);

    let args: Vec<String> = std::env::args().skip(1).collect();
    for arg in args {{
        cmd.arg(arg);
    }}

    match cmd.status() {{
        Ok(status) => std::process::exit(status.code().unwrap_or(1)),
        Err(e) => {{
            eprintln!("Uygulama başlatılamadı: {{}}", e);
            eprintln!("Python binary: {{}}", python_bin.display());
            eprintln!("Script: {{}}", script_path.display());
            std::process::exit(1);
        }}
    }}
}}
"#,
        app_name = app_name,
        script_name = script_name,
    )
}

/// Launcher'ı hedef platform için oluşturur
pub fn create_launcher(
    output_dir: &Path,
    target: &Target,
    app_name: &str,
    script_name: &str,
) -> Result<(), String> {
    match target.os {
        OperatingSystem::Windows => create_windows_launcher(output_dir, app_name, script_name),
        _ => create_unix_launcher(output_dir, app_name, script_name),
    }
}

/// README dosyası oluşturur
pub fn create_readme(output_dir: &Path, app_name: &str, target: &Target) -> Result<(), String> {
    let readme = format!(
        r#"# {app_name}

## Python Runtime Bundle

This package includes every module that is
needed to make {app_name} run independently.

- Python runtime (standalone build)
- Application code
- Dependencies

## Platform: {target}

## Usage

### Linux / macOS
```bash
./{app_name}
```

### Windows
```bat
{app_name}.bat
```

### PowerShell
```powershell
.\{app_name}.ps1
```
Directory Tree

{app_name}/
├── {app_name}          # Linux/macOS launcher
├── {app_name}.bat      # Windows launcher
├── {app_name}.ps1      # PowerShell launcher
├── python/             # Python runtime
│   ├── bin/            # Python binary (Linux/macOS)
│   ├── lib/            # Python libraries
│   └── python.exe      # Python binary (Windows)
├── app/                # Application code
│   └── main.py         # Main script
├── lib/                # Extra libraries
└── launcher_src/       # Rust launcher source code
    └── main.rs

System requirements

    {target} compatible operating system

This package is created with pypack
"#,
app_name = app_name,
target = target,
);

fs::write(output_dir.join("README.md"), readme)
    .map_err(|e| format!("Couldn't create README.md: {}", e))?;

Ok(())

}